name: virtualFit
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip=21.1.3
  - python=3.8.12
  - pip:
    - playsound==1.2.2
    - notebook
    - mediapipe
    - pandas
    - opencv-python
    - streamlit
    - gTTS
    - joblib==1.0.1
    - xgboost==1.5.2
    - scikit-learn==0.24.2
    - pygobject
