name: virtualFit
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip=24.0
  - python=3.11
  - pip:
    - playsound
    - notebook
    - mediapipe
    - pandas
    - opencv-python
    - streamlit
    - gTTS
    - joblib
    - scikit-learn
    - multiprocess
